version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.9.0
        environment:
          MIX_ENV: test

    working_directory: ~/app

    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force

      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v2-build-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v2-build-cache-{{ .Branch }}
            - v2-build-cache
      - run: mix do deps.get, compile --warnings-as-errors, dialyzer.build
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: ["deps"]
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: ["deps"]
      - save_cache:
          key: v1-mix-cache
          paths: ["deps"]
      - save_cache:
          key: v2-build-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: ["_build"]
      - save_cache:
          key: v2-build-cache-{{ .Branch }}
          paths: ["_build"]
      - save_cache:
          key: v2-build-cache
          paths: ["_build"]

      - run: mix coveralls.circle -u # This will run and report tests as usual, too
      - run: mix dialyzer --format short --halt-exit-status
      - run: mix credo
      - run: mix format --check-formatted

      - store_test_results:
          path: _build/test/junit
